--- #YAML:1.0
name:                WebService-RTMAgent
version:             0.5_1
abstract:            ~
license:             ~
author:              
    - Yves Rutschle <cpan@rutschle.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Digest::MD5:                   0
    LWP::UserAgent:                0
    Test::More:                    0
    XML::SAX:                      0
    XML::Simple:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
