# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-RTMAgent
version:      0.5
version_from: lib/WebService/RTMAgent.pm
installdirs:  site
requires:
    Digest::MD5:                   0
    LWP::UserAgent:                0
    Test::More:                    0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
