---
abstract: 'a user agent for the Remember The Milk API'
author:
  - 'Yves Rutschle'
build_requires:
  Data::Dumper: 0
  English: 0
  File::Copy: 0
  File::Spec: 0
  File::Temp: 0
  HTTP::Response: 0
  HTTP::Status: 0
  Test::More: 0.96
  base: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-RTMAgent
requires:
  Carp: 0
  Digest::MD5: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  XML::Simple: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/rjbs/WebService-RTMAgent/issues
  homepage: https://github.com/rjbs/WebService-RTMAgent
  repository: https://github.com/rjbs/WebService-RTMAgent.git
version: 0.600
x_Dist_Zilla:
  perl:
    version: 5.019005
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@RJBS/Git::GatherDir'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@RJBS/CheckPrereqsIndexed'
      version: 0.009
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@RJBS/CheckExtraTests'
      version: 0.015
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      name: '@RJBS/RJBS-Outdated'
      version: 0.011
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      name: '@RJBS/CPAN-Outdated'
      version: 0.011
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@RJBS/@Filter/PruneCruft'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@RJBS/@Filter/ManifestSkip'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@RJBS/@Filter/MetaYAML'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::License
      name: '@RJBS/@Filter/License'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@RJBS/@Filter/Readme'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@RJBS/@Filter/ExecDir'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@RJBS/@Filter/ShareDir'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@RJBS/@Filter/MakeMaker'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@RJBS/@Filter/Manifest'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@RJBS/@Filter/TestRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@RJBS/@Filter/ConfirmRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@RJBS/@Filter/UploadToCPAN'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@RJBS/AutoPrereqs'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@RJBS/Git::NextVersion'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@RJBS/PkgVersion'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@RJBS/MetaConfig'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@RJBS/MetaJSON'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@RJBS/NextRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Test::ChangesHasContent
      name: '@RJBS/Test::ChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@RJBS/PodSyntaxTests'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@RJBS/ReportVersions::Tiny'
      version: 1.10
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@RJBS/TestMoreWithSubtests'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          config_plugin: '@RJBS'
          finder:
            - ':InstallModules'
            - ':ExecFiles'
      name: '@RJBS/PodWeaver'
      version: 4.001
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@RJBS/GithubMeta'
      version: 0.42
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@RJBS/@Git/Check'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@RJBS/@Git/Commit'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@RJBS/@Git/Tag'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@RJBS/@Git/Push'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.006
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.006
